### ISSUE TITLE
Difference in formatting compared to `nixpkgs-fmt`

### ISSUE THREAD

**Issue by fufexan** [nix-community/rnix-lsp#47]
As far as I understand, `rnix-lsp` uses `nixpkgs-fmt` for formatting (on write). However, I get different outputs when I save a nix file in my editor vs when I manually run `nixpkgs-fmt` over a dir/file.

The most notable example is:
nixpkgs-fmt | rnix-lsp
---|---
`[ ] { }` | `[] {}`

Is there a way to configure `rnix-lsp`'s formatting options or is there some other issue at hand?

**Comment by Ma27** [comment]
Which version of `rnix-lsp` do you use? 0.1.0 or `master` (soon 0.2.0)? If you're on 0.1.0 it's most likely due to the fact that it uses an older version of `nixpkgs-fmt`.

At least I cannot reproduce this on my neovim 0.5.0 with latest master of `rnix-lsp`. The other option would be that some autoformatting of your editor interferes with what `rnix-lsp` does.

**Comment by fufexan** [comment]
It seems that indeed I am using 0.1.0. Thanks for telling me, I'll update it manually.
